const TITLE_SCHEMA_SQL = `
CREATE TABLE IF NOT EXISTS titles (
    title_id INTEGER GENERATED BY DEFAULT AS IDENTITY (START WITH 3) PRIMARY KEY CHECK (title_id > 1),
    name VARCHAR(24) NOT NULL UNIQUE CHECK (length(btrim(name)) > 0),
    description VARCHAR(200) NOT NULL DEFAULT '',
    is_enabled BOOLEAN NOT NULL DEFAULT TRUE,
    sort_order INTEGER NOT NULL DEFAULT 0,
    created_at TIMESTAMPTZ NOT NULL DEFAULT CURRENT_TIMESTAMP,
    updated_at TIMESTAMPTZ NOT NULL DEFAULT CURRENT_TIMESTAMP
);
CREATE TABLE IF NOT EXISTS user_titles (
    user_id BIGINT NOT NULL REFERENCES users(user_id) ON DELETE CASCADE,
    title_id INTEGER NOT NULL REFERENCES titles(title_id),
    granted_by BIGINT REFERENCES users(user_id) ON DELETE SET NULL,
    granted_at TIMESTAMPTZ NOT NULL DEFAULT CURRENT_TIMESTAMP,
    grant_reason VARCHAR(500) NOT NULL DEFAULT '',
    PRIMARY KEY (user_id, title_id)
);
CREATE INDEX IF NOT EXISTS idx_user_titles_title ON user_titles(title_id);
INSERT INTO titles (title_id, name, description) VALUES (2, '最初的初段', '初始头衔') ON CONFLICT DO NOTHING;
UPDATE titles SET name = '最初的初段', updated_at = CURRENT_TIMESTAMP
WHERE title_id = 2 AND name = '初段'
  AND NOT EXISTS (SELECT 1 FROM titles WHERE name = '最初的初段');
INSERT INTO user_titles (user_id, title_id, grant_reason)
SELECT us.user_id, us.title_id, '迁移原有佩戴头衔'
FROM user_settings us JOIN titles t ON t.title_id = us.title_id
ON CONFLICT (user_id, title_id) DO NOTHING;
`;

async function ensureTitleTables(db = require('../config/database')) {
  // One transaction also makes schema initialization safe against partial startup.
  const client = await db.connect();
  try {
    await client.query('BEGIN');
    await client.query(TITLE_SCHEMA_SQL);
    await client.query('COMMIT');
  } catch (error) {
    await client.query('ROLLBACK');
    throw error;
  } finally { client.release(); }
}

module.exports = { TITLE_SCHEMA_SQL, ensureTitleTables };
