export const UNITY_PANELS = [
  { key: 'NetworkManagerSim', name: 'GameStateNetworkManager' },
  { key: 'GsmSim', name: 'NormalGameStateManager' },
  { key: 'BoardCanvasSim', name: 'BoardCanvas' },
  { key: 'GameCanvasSim', name: 'GameCanvas' },
  { key: 'ActionButtonSim', name: 'ActionButton' },
  { key: 'TimerSim', name: 'GameCanvas.Timer' },
  { key: 'ActionDisplaySim', name: 'GameCanvas.ActionDisplay' },
  { key: 'Game3DSim', name: 'Game3DManager' },
  { key: 'TipsSim', name: 'TipsBlock' },
  { key: 'EndResultSim', name: 'EndResultPanel' },
  { key: 'VoteSim', name: 'VotePanel' },
]

export const OPEN_DEFAULT = ['GsmSim', 'ActionButtonSim']

export const ACTION_TEXT = {
  peng: '碰',
  gang: '杠',
  hu_self: '自摸',
  hu_flower: '花胡',
  initial_hu: '起手胡',
  sea_bottom: '要海底',
  hu: '和',
  hu_first: '和',
  hu_second: '和',
  hu_third: '和',
  buhua: '补花',
  angang: '暗杠',
  buzhang: '补张',
  jiagang: '加杠',
  chi_left: '吃',
  chi_mid: '吃',
  chi_right: '吃',
  jiuzhongjiupai: '九老峰回',
  riichi_cut: '立直',
  pass: '取消',
  force_pass: '放弃',
  ready: '准备',
  cut: '切',
}
