CREATE TABLE IF NOT EXISTS item_definitions (
    item_id INTEGER GENERATED BY DEFAULT AS IDENTITY (START WITH 4000) PRIMARY KEY,
    code VARCHAR(64) NOT NULL UNIQUE,
    name VARCHAR(32) NOT NULL,
    description VARCHAR(300) NOT NULL DEFAULT '',
    category VARCHAR(16) NOT NULL CHECK (category IN ('character','item','cosmetic')),
    asset_key VARCHAR(80) NOT NULL,
    slot VARCHAR(24) NOT NULL DEFAULT '',
    max_quantity INTEGER NOT NULL CHECK (max_quantity BETWEEN 1 AND 1000000),
    is_default BOOLEAN NOT NULL DEFAULT FALSE,
    grant_enabled BOOLEAN NOT NULL DEFAULT TRUE,
    use_enabled BOOLEAN NOT NULL DEFAULT TRUE,
    sort_order INTEGER NOT NULL DEFAULT 0,
    config JSONB NOT NULL DEFAULT '{}',
    created_at TIMESTAMPTZ NOT NULL DEFAULT CURRENT_TIMESTAMP,
    updated_at TIMESTAMPTZ NOT NULL DEFAULT CURRENT_TIMESTAMP
);
CREATE TABLE IF NOT EXISTS user_inventory (
    user_id BIGINT NOT NULL REFERENCES users(user_id) ON DELETE CASCADE,
    item_id INTEGER NOT NULL REFERENCES item_definitions(item_id),
    quantity INTEGER NOT NULL CHECK (quantity BETWEEN 0 AND 1000000),
    acquired_at TIMESTAMPTZ NOT NULL DEFAULT CURRENT_TIMESTAMP,
    updated_at TIMESTAMPTZ NOT NULL DEFAULT CURRENT_TIMESTAMP,
    PRIMARY KEY (user_id,item_id)
);
CREATE TABLE IF NOT EXISTS user_equipment (
    user_id BIGINT NOT NULL REFERENCES users(user_id) ON DELETE CASCADE,
    slot VARCHAR(24) NOT NULL CHECK (slot IN ('character','avatar','avatar_frame')),
    item_id INTEGER NOT NULL REFERENCES item_definitions(item_id),
    updated_at TIMESTAMPTZ NOT NULL DEFAULT CURRENT_TIMESTAMP,
    PRIMARY KEY (user_id,slot)
);
CREATE TABLE IF NOT EXISTS inventory_operations (
    operation_id UUID PRIMARY KEY,
    user_id BIGINT NOT NULL REFERENCES users(user_id) ON DELETE CASCADE,
    request_id VARCHAR(64) NOT NULL,
    request_hash VARCHAR(64) NOT NULL,
    action VARCHAR(32) NOT NULL,
    actor_id BIGINT,
    reason VARCHAR(500) NOT NULL DEFAULT '',
    result JSONB NOT NULL DEFAULT '{}',
    created_at TIMESTAMPTZ NOT NULL DEFAULT CURRENT_TIMESTAMP,
    UNIQUE (user_id,request_id)
);
CREATE TABLE IF NOT EXISTS inventory_ledger (
    entry_id BIGSERIAL PRIMARY KEY,
    operation_id UUID NOT NULL REFERENCES inventory_operations(operation_id) ON DELETE CASCADE,
    user_id BIGINT NOT NULL REFERENCES users(user_id) ON DELETE CASCADE,
    item_id INTEGER NOT NULL REFERENCES item_definitions(item_id),
    delta INTEGER NOT NULL,
    quantity_after INTEGER NOT NULL CHECK (quantity_after >= 0),
    created_at TIMESTAMPTZ NOT NULL DEFAULT CURRENT_TIMESTAMP
);
CREATE INDEX IF NOT EXISTS idx_inventory_ledger_user ON inventory_ledger(user_id,entry_id DESC);
CREATE INDEX IF NOT EXISTS idx_user_inventory_item ON user_inventory(item_id);
CREATE INDEX IF NOT EXISTS idx_user_equipment_item ON user_equipment(item_id);
